site_name: DELTA_CODE.ID
theme:
  name: material

nav:
  - Beranda: index.md
  - Pemula (Beginner):
      - Instalasi: Instalasi.md
      - Variabel dan Tipe Data: Variabel dan Tipe Data.md
      - Kontrol Alur Program: Kontrol Alur Program.md
      - Fungsi: Fungsi.md
      - Struktur Data: Struktur Data.md
      - File Handling: File Handling.md
      - Error Handling & Debugging: Error Handling & Debugging.md

  - Level Up Skill (Intermediate):
      - Program Modular: Program Modular.md
      - Pemrograman Berbasis Objek: Pemrograman Berbasis Objek.md
      - Multi Threading & Async Programming: Multi Threading & Async Programming.md
      - Database & ORM: Database & ORM.md
      - List Comprehension: List Comprehension.md
      - Best Practices dalam Python Programming: Best Practices dalam Python Programming.md
      - Unit Testing dan TTD : Unit Testing dan TTD.md
      - Environment Management: Environment Management.md
      - Packaging & Management: Packaging & Management.md
      - Logging & Monitoring: Logging & Monitoring.md
      - Security dalam Python Web Dev : Security dalam Python Web Dev.md
      - Design Pattern: Design Pattern.md

  - Level Skill Dewa (Advanced):
      - API & Web Development: API & Web Development.md
      - Python untuk Otomasi: Python untuk Otomasi.md
      - Python untuk Cybersecurity: Python untuk Cybersecurity.md
      - Python untuk Game Development: Python untuk Game Development.md
      - Python untuk Internet of Things (IoT): Python untuk Internet of Things (IoT).md
      - Python untuk Data Science: Python untuk Data Science.md
      - Data Science & Machine Learning: Data Science & Machine Learning.md
      - Python untuk Machine Learning: Python untuk Machine Learning.md
      - Artificial Intelligence & Deep Learning: Artificial Intelligence & Deep Learning.md
      - Deployment Model AI ke Web & Mobile: Deployment Model AI ke Web & Mobile.md
      - Python untuk Blockchain & Cryptocurrency: Python untuk Blockchain & Cryptocurrency.md

  - Tips dan Trik:
      - Best Practices Python: Best Practices dalam Python Programming.md
      - Tips dan Trik: Tips dan Trik.md

markdown_extensions:
  - attr_list
  - codehilite  # Tambahkan agar syntax highlight pada kode lebih bagus
